### ISSUE TITLE
Use session to find tenant

### ISSUE THREAD

**Issue by bremg** [spatie/laravel-multitenancy#105]
I would like to do something like this: 

```php
class SessionTenantFinder extends TenantFinder
{
    use UsesTenantModel;

    public function findForRequest(Request $request): ?Tenant
    {
        if ($request->session()->has('active_website')) {
            
            $activeSiteName =  $request->session()->get('active_website');
            
            return $this->getTenantModel()::where('name', $activeSiteName)->first();
        }

        return null;
    }
}
```

Also tried using Auth::user() but that returns null..

Alas I cannot get the session to work. Is it at all possible? Or is there a better approach to solve this?

I cannot use the host name, since this won't change..

**Comment by masterix21** [comment]
The package executes the `TenantFinder` from the service provider. Laravel starts all session from the middleware `\Illuminate\Session\Middleware\StartSession::class`. 

These two definitions are useful to understand that you can't access a session from a service provider because the service provider runs before the `StartSession` middleware.

Implement your code ignoring the `TenatFinder` in favor of a custom middleware with the same logic of your `SessionTenantFinder`.

**Comment by bremg** [comment]
Thanks a million! 

I made a new middleware like you said and included it in the tenant middleware group. 

The middleware works like this: 


    public function handle($request, Closure $next)
    {
        if ($request->session()->has('active_website')) {

            $activeSiteName =  $request->session()->get('active_website');

            /** @var Tenant $tenant */
            $tenant = $this->getTenantModel()::where('name', $activeSiteName)->first();
            $tenant->makeCurrent();
        }

        return $next($request);
    }

**Comment by masterix21** [comment]
Great! Thanks for your share.

**Comment by alexv96** [comment]
Hello how are you? a query to make the identification of the tenant apart from the middleware that you share did some other configuration, I'm new to this and I can not make the connection for sessions I do not know if I should create a custom tenant that extends the tenant of the library, could you help me?
