### ISSUE TITLE
Run tenants:artisan command via Code

### ISSUE THREAD

**Issue by shahvirag** [spatie/laravel-multitenancy#120]
`Artisan::call('tenants:artisan "migrate --database=tenant --force"');`

Run same command via console works fine.

If we run it via code it's not importing any migrations.

**Comment by masterix21** [comment]
Are you executing the code from an environment with the tenant up?

Example:
```php
Tenant::first()->execute(function() {
    Artisan::call('tenants:artisan "migrate --database=tenant --force"');
});
```

**Comment by shahvirag** [comment]
Yes. on creating new tenant create a database and then migrate.
>> database create is complete. but migration is not complete

**Comment by masterix21** [comment]
Please post your code

**Comment by shahvirag** [comment]
>Custom Tenant model Code

```
public static function booted()
{
    static::creating(function ($model) {
        $model->createDatabase();
        $model->runMigration();
    });
}

protected function createDatabase()
{
    $createDbSql = "CREATE DATABASE {{ db_name }} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci";

    DB::statement(str_replace('{{ db_name }}', $this->database, $createDbSql));
}

protected function runMigration()
{
    Artisan::call('tenants:artisan "migrate --database=tenant"');
}
```

**Comment by telkins** [comment]
@shahvirag I do more or less the same thing.  Here are a few observations:

First, I'm pretty sure that you won't have an actual tenant in your landlord database during the `creating` event.  It's only **after** that that it's written to the database.

As I said, I'm doing the same thing, but I do it during the tenant's `created` event.  My guess is that you'll need to do the same since, according to the docs, the "command will loop over tenants and for each of them make that tenant current, and execute the artisan command."  If it's not in the database, then it won't be executed for the made-but-not-created tenant.

Second, I had problems running the migration, too.  I first tried the same basic thing you did...I just did it for the specific tenant:
```php
Artisan::call('tenants:artisan "migrate --database=tenant" --tenant=' . $tenant->id);
```

I still don't know why it wasn't working, but I tried the alternative and it works just fine:
```php
Artisan::call('tenants:artisan', [
    'artisanCommand' => 'migrate --database=tenant --force',
    '--tenant' => $tenant->id,
]);
```

(I also appear to have added `--force`, but that shouldn't matter...in fact, I think I could/should remove it. 🤓)

And finally, you **may** want to consider doing this stuff in a job.  That's what I've elected to do.  That has nothing to do with your issues, but it still might be something to consider.

Give those things a try and let us know whether or not that helps.  👍 💪 🤓

**Comment by masterix21** [comment]
> First, I'm pretty sure that you won't have an actual tenant in your landlord database during the `creating` event. It's only **after** that that it's written to the database.

I agree with @telkins

**Comment by shahvirag** [comment]
Oh Gotcha...calling it on wrong event....
thanks for pointing out issue @telkins and @masterix21 

> @shahvirag I do more or less the same thing. Here are a few observations:
> 
> First, I'm pretty sure that you won't have an actual tenant in your landlord database during the `creating` event. It's only **after** that that it's written to the database.
> 
> As I said, I'm doing the same thing, but I do it during the tenant's `created` event. My guess is that you'll need to do the same since, according to the docs, the "command will loop over tenants and for each of them make that tenant current, and execute the artisan command." If it's not in the database, then it won't be executed for the made-but-not-created tenant.
> 
> Second, I had problems running the migration, too. I first tried the same basic thing you did...I just did it for the specific tenant:
> 
> ```
> Artisan::call('tenants:artisan "migrate --database=tenant" --tenant=' . $tenant->id);
> ```
> 
> I still don't know why it wasn't working, but I tried the alternative and it works just fine:
> 
> ```
> Artisan::call('tenants:artisan', [
>     'artisanCommand' => 'migrate --database=tenant --force',
>     '--tenant' => $tenant->id,
> ]);
> ```
> 
> (I also appear to have added `--force`, but that shouldn't matter...in fact, I think I could/should remove it. 🤓)
> 
> And finally, you **may** want to consider doing this stuff in a job. That's what I've elected to do. That has nothing to do with your issues, but it still might be something to consider.
> 
> Give those things a try and let us know whether or not that helps. 👍 💪 🤓
