### ISSUE TITLE
How to manually define tenant database cofiguration?

### ISSUE THREAD

**Issue by devianleong** [spatie/laravel-multitenancy#186]
I am hosting my application on cloud server with multi-databases setting. Each clients are having independent database and AWS S3 bucket settings (IAM JSON file) for their website content. Can anyone share with me:

1) How to switch connection based on different tenant hostname, db username and password?
2) How to store and switch AWS configuration based on JSON file for each tenant? (Originally json file path was stored in env file)
3) How cron job and and queue job works? 

Question above I could not find any answer in the document. Sorry the question has been asked by some other

**Comment by masterix21** [comment]
Hi @devianleong.

1. You should create your custom one `SwitchTenantDatabaseTask`
2. You should extend your `Domain` model with all missing columns (DB username, password, etc.)
3. It Works like a normal Laravel application, but please read the documentation.

I'm closing the issue because it isn't related to a package problem, but feel free to continue talking. Thanks.
