### ISSUE TITLE
Default database in multi database setup

### ISSUE THREAD

**Issue by James4645** [spatie/laravel-multitenancy#262]
Curious if there's any difference in setting the default DB connection. Like is there a reason to make it the tenant or the landlord or is it pretty irrelevant?

**Comment by masterix21** [comment]
If your code is well organized, there are no differences, but - for me - the default connection should always be available: for this reason, I'm always using landlord as the default connection; but it’s my opinion.

**Comment by masterix21** [comment]
I'm closing here because isn't related to a package issue, but feel free to continue with your discussion. Thanks.

**Comment by 77media-creations** [comment]
> If your code is well organized, there are no differences, but - for me - the default connection should always be available: for this reason, I'm always using landlord as the default connection; but it’s my opinion.

Setting 'landlord' as the default connection doesn't work for me. 
The package seems to set the tenant database name on the tenant connection array in config (when a tenant is found), but due to the default connection set to 'landlord', the request is connecting to the landlord db even though tenant database name is dynamically set in config.

And the result of this, submitting login form leads to the error saying "Table 'landlord.users' doesn't exist".
