### ISSUE TITLE
php artisan test -p throws error

### ISSUE THREAD

**Issue by sajendramanandhar** [spatie/laravel-multitenancy#350]
I ran `sail shell` and then ran `php artisan test`. This runs fine. I also ran `sail artisan test` in my local terminal, it also runs fine, but when I run `php artisan test -p` or `sail artisan test -p`, all of my tests fail and I get this error: `Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'sail'@'%' to database '_test_4' (SQL: drop database if exists _test_4)`.

I am using **Ubuntu 20.04** , **Laravel Sail** and **MySQL** database for testing.

Thank you for taking a look at it.

![Screenshot from 2022-03-29 14-12-20](https://user-images.githubusercontent.com/17451246/160568461-d855535c-98f9-4fc8-8e29-2fc77dcbb172.png)
![Screenshot from 2022-03-29 14-13-20](https://user-images.githubusercontent.com/17451246/160568478-18d01777-d118-4a51-aa3d-513c28e4ad1d.png)

**Comment by masterix21** [comment]
I think you can't use the parallel tests with a MySQL database because data and structure are shared across all your tests. So, what happens if the first test drops your database (or migrates it again) when the second - parallel - test needs it? 

Also using the transactions, these don't roll back your schema changes. So I think is hard to help you with your parallel tests without understanding better what your tests really do.

@freekmurze what's your opinion on it?

**Comment by freekmurze** [comment]
I think the problem is dat Laravel only takes care of the default db connection.

From the docs: 

> Laravel automatically handles creating and migrating a test database for each parallel process that is running your tests. The test databases will be suffixed with a process token which is unique per process. For example, if you have two parallel test processes, Laravel will create and use your_db_test_1 and your_db_test_2 test databases.

We would need to do this with the tenant and landlord db's as well (or make Laravel aware it should handle those db's as well). Some more info on how we could hook into this process: https://laravel.com/docs/master/testing#parallel-testing-hooks

I don't know if it's feasible, but would be nice if the package would take care of it out of the box.
