### ISSUE TITLE
[Question] Tenants with custom domain

### ISSUE THREAD

**Issue by asivaneswaran** [spatie/laravel-multitenancy#37]
Hi,

I looked into your package and it's amazing by the way. I was wondering how you would suggest handling clients with their own domain name? How can we figure out the current tenant?

**Comment by ammadeuss** [comment]
“ The package ships with a DomainTenantFinder that will make the tenant active who’s domain attribute value matches the host of the current request.”

 - from https://docs.spatie.be/laravel-multitenancy/v1/installation/determining-current-tenant/

**Comment by asivaneswaran** [comment]
Sorry, it might not have been clear.

I know it can detect: site1.website.com, site2.website.com, etc. But what if there is some sites that site1.com and site2.com?

**Comment by vincenzoraco** [comment]
The `DomainTenantFinder` class will get the full domain by default (see https://docs.spatie.be/laravel-multitenancy/v1/basic-usage/automatically-determining-the-current-tenant/) using `$request->getHost()` which returns the full domain including any subdomains, so if your user is using a custom domain, set the `$user->domain` to `custom.com` instead of `user.yourdomain.com`.
