### ISSUE TITLE
How to: phpunit tests

### ISSUE THREAD

**Issue by dseeger** [spatie/laravel-multitenancy#71]
How to I run my phpunit tests with laravel-multitenancy
So far I had them running with a sqlite database just for testing puposes. How should i setup testing now?

**Comment by masterix21** [comment]
You can test using MySQL: see the tests already available in the package.

https://github.com/spatie/laravel-multitenancy/blob/master/tests/TestCase.php

**Comment by bryanjamesmiller** [comment]
@masterix21 thanks for being so responsive on this repository.  I too am having a heck of a time setting up basic phpunit tests on a brand new, simple Laravel 8 app.  

I read through several other issues regarding testing in the issues, but nothing seems to be working for me.  I know you recommended taking a look at the tests in the package, but that seems a lot different than setting up testing in a basic Laravel project since it is using Orchestra for instance.  

I saw another issue where someone made a demo repository with working tests at https://github.com/CasperBE/tenancytest, however it's a little outdated as it's locked in at  "version": "1.3.0" and doesn't work in my app.

Like the above though, it would be super cool if you could do something similar with just the most basic install where you have phpunit running in a laravel app.  Maybe a test could create a tenant on the landlords DB.  Maybe another test could create a user on a tenant DB.  

I think that would be a lot easier than me trying to walk you through all the issues I'm having.  Here's what my testing setup looks like so far, but feel free to do something totally different if you feel like I've got a bad approach here.  If you don't want to spin up a quick example Laravel 8 project demoing phpunit tests, I totally understand and maybe you can still give me some feedback regarding the below:

tests/Unit/TenantCreationTest.php
```
<?php

namespace Tests\Unit;

use App\Models\Tenant;
use PHPUnit\Framework\TestCase;

class TenantCreationTest extends TestCase
{
    public function testATenantCanBeCreated()
    {
        $tenant = Tenant::factory()->create();

        $this->assertDatabaseHas('tenants', [
            'name' => $tenant->name,
            'domain' => $tenant->domain,
            'database' => $tenant->database,
        ]);
    }
}

```

tests/TestCase.php
```
<?php

namespace Tests;

use App\Models\Tenant;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp();

        $this->migrateLandlordDatabase();
        $this->migrateFirstTenantDatabase();
        $this->migrateSecondTenantDatabase();
    }

    protected function migrateLandlordDatabase()
    {
        config()->set('database.connections.landlord.database', 'landlord_testing');

        $this->artisan('migrate:fresh --database=landlord --path=database/migrations/landlord')
            ->assertExitCode(0);

        Tenant::factory()->create([
            'name' => 'Tenant One',
            'domain' => 'tenant-one.my-domain.test',
            'database' => 'tenant_testing_1',
        ]);

        Tenant::factory()->create([
            'name' => 'Tenant Two',
            'domain' => 'tenant-two.my-domain.test',
            'database' => 'tenant_testing_2',
        ]);
    }

    protected function migrateFirstTenantDatabase()
    {
        $this->artisan('migrate:fresh --database=tenant --path=database/migrations/tenants')
            ->assertExitCode(0);
    }

    protected function migrateSecondTenantDatabase()
    {
        config()->set('database.connections.tenant.database', 'tenant_testing_2');
        $this->artisan('migrate:fresh --database=tenant --path=database/migrations/tenants')
            ->assertExitCode(0);
    }
}

```

app\Models\Tenant.php
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\Multitenancy\Models\Concerns\UsesLandlordConnection;

class Tenant extends \Spatie\Multitenancy\Models\Tenant
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'domain',
        'database',
    ];
}

```

**Comment by bryanjamesmiller** [comment]
Hmm I solved one issue I was having.  I had to specify the connection when doing an assertion:

```
        $this->assertDatabaseHas('tenants', [
            'name' => $tenant->name,
            'domain' => $tenant->domain,
            'database' => $tenant->database,
        ], 'landlord');
```

That 'landlord' 3rd parameter at the end was missing and I guess necessary?  I was expecting the assertion to already be set depending on the value of Tenant::current() and if null, then know to use the 'landlord' connection automatically.
